#!/bin/bash

# My aliases
alias ll='ls -l'
alias lf='ls -lsA'
alias mv='mv -iv'
alias cp='cp -iv'
alias rm='rm -v'
alias snano='sudo nano'
alias svi='sudo vi'
alias pf='ps -efl | grep'
alias iftw='TERM=xterm sudo iftop -p -i wlp0s20f3 -f "not ether host ff:ff:ff:ff:ff:ff"'
alias web='lynx -cfg=~/.lynx/lynx.cfg -show-rate'
alias fresh='~/bin/fresh.sh'
alias aptf='sudo aptitude search'
alias apti='sudo aptitude install'
alias apts='sudo aptitude show'
alias aptr='sudo aptitude remove'
alias sapt='sudo aptitude'
alias dpi='sudo dpkg -i'
alias procs='sudo htop -d 20'
alias stats='sudo atop 5'
alias load='sudo iotop -o --processes'
alias cgpu='gpustat -cup -i 5'
alias ipts='sudo iptstate -L'
alias logs='sudo multitail /var/log/syslog -i /var/log/messages'
alias rando='cat /dev/urandom | tr -dc "a-zA-Z0-9" | fold -w ${1:-32} | head -n 1'
alias vdl='youtube-dl'
alias shls='env | grep SHLVL'
alias nofo='gsettings set org.gnome.desktop.app-folders folder-children []'
alias dupes='find . ! -empty -type f -exec md5sum {} + | sort | uniq -w32 -dD'
alias usage='df -k | grep -v loop'
alias dirt='watch -d grep -e Dirty: /proc/meminfo'
alias mkc='minikube kubectl --'
alias sdo='sudo docker'
